version: '3.9'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nest-test
      POSTGRES_USER: nest-test
      POSTGRES_PASSWORD: super-secret-password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nest-test']
      interval: 5s
      timeout: 3s
      retries: 5
    # Persist database content between runs
    volumes:
      - nest-test-pgdata:/var/lib/postgresql/data

volumes:
  nest-test-pgdata:
